packages:
  - .
  - cli
  - docs

allowBuilds:
  '@atcute/time-ms': true
  '@parcel/watcher': false
  '@resvg/resvg-js': true
  'better-sqlite3': true
  'core-js': false
  'esbuild': false
  msw: true
  sharp: true
  'unrs-resolver': false
  'vue-demi': false

catalogs:
  msw:
    'msw': '^2.13.2'

  storybook:
    '@storybook-vue/nuxt': 'https://pkg.pr.new/@storybook-vue/nuxt@1021'
    '@storybook/addon-a11y': '^10.3.5'
    '@storybook/addon-docs': '^10.3.5'
    '@storybook/addon-themes': '^10.3.5'
    'msw-storybook-addon': '^3.0.0'
    'storybook': '^10.3.1'
    'storybook-i18n': '^10.1.1'

  vite-plus:
    'vite': npm:@voidzero-dev/vite-plus-core@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de
    'vite-plus': 0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de
    'vitest': 4.1.11
    '@vitest/browser-playwright': 4.1.11
    '@vitest/coverage-v8': 4.1.11

dedupePeers: true

ignoreDepScripts: true

ignoreWorkspaceRootCheck: true

minimumReleaseAgeExclude:
  - '@iconify-json/simple-icons@1.2.93'
  - 'nuxt@4.5.2'
  - '@nuxt/kit@4.5.2'
  - '@nuxt/nitro-server@4.5.2'
  - '@nuxt/schema@4.5.2'
  - '@nuxt/vite-builder@4.5.2'
  - vue-data-ui@3.25.0
  - '@voidzero-dev/vite-plus-core@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-darwin-x64@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de'
  - vite-plus@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de

minimumReleaseAgeExcludePrune: true

overrides:
  '@types/node': 24.13.3
  nuxt-og-image: ^6.7.5
  sharp: 0.35.3
  vue: 3.5.42
  typescript: npm:typescript-native-bridge@6.0.3-bridge.13.tsgo.7.0.2
  vue-router: 5.2.0
  markdown-exit: 1.1.0-beta.2
  oxc-parser: 0.144.0
  '@nuxtjs/i18n>@nuxt/kit': '4.5.2'
  vite@*: catalog:vite-plus
  vitest@*: catalog:vite-plus

packageExtensions:
  '@nuxt/scripts':
    dependencies:
      estree-walker: ^3.0.3

patchedDependencies:
  '@jsr/deno__doc@0.189.1': patches/@jsr__deno__doc@0.189.1.patch
  '@nuxt/test-utils@4.1.0': patches/@nuxt__test-utils@4.1.0.patch

savePrefix: ''

shellEmulator: true
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
